runtime: static
handlers:
  - url: /.*
    static_files:
      path: techeeta-analytics/client/build
      upload_path: techeeta-analytics/client/build
    expiration: "1d"  # Cache static files for 1 day
